### ISSUE TITLE
Add UDP client connection

### ISSUE THREAD

**Issue by Vavooon** [MishkaRogachev/JAGCS#29]
Hi. Please add possibility to specify IP address for UDP connections (maybe it would be better to divede UDP connections to UDP client connection  and UDP server connection).
Please keep in mind that GCS should emit Mavlink heartbeats in order to be discovered by other side in such mode.

**Comment by MishkaRogachev** [comment]
Hi! Current UDP link use this strategy: it is waiting incoming(from MAV) messages on specified port from any address and on receive add sender's address and port to endpoints list. When one or more endpoints obtained, it emits GCS heartbeats and commands on all addresses/ports from the list. 
I can add advanced link configuration, where user can add static receivers adresses and ports manualy.

**Comment by Vavooon** [comment]
Thanks, I understand the logic how it works now.
I'm asking about possibility to initiate connection from GCS because it is easier (you'll need to reconfigure your MavLink streaming software instead).
So you, please add a way to specify IP address. I think it would be even better to have 2 UDP connection types (server and client or master and slave).
Thank you.

**Comment by Vavooon** [comment]
Hi. In case you're busy may I ask you just to spot places in code where I'd be able to add UDP client support?

**Comment by MishkaRogachev** [comment]
I will add UDP connection configuration soon, in few weeks i think. Temporary you can add static ip/port to [udp_link](https://github.com/MishkaRogachev/JAGCS/blob/master/sources/communication/links/udp_link.cpp)

**Comment by MishkaRogachev** [comment]
Fixed [here](https://github.com/MishkaRogachev/JAGCS/commit/3488d2c384d59a84da16227924e1f96f625f6b6c)

**Comment by Vavooon** [comment]
Thank you, however now I have another problem and can't test the change. I'll create another ticket.
