### ISSUE TITLE
Can JAGCS supports multi vehicle?

### ISSUE THREAD

**Issue by JeimeRhee** [MishkaRogachev/JAGCS#30]
Hello I'm using JAGCS downloaded when November 20. 2017

I analyzed JAGCS source code, It seems supports multi vehicle.

If you tested about controlling multi vehicle, can you tell me how to connect JAGCS with multi vehicle?

And in the planning view, can I see connected all vehicle's mission item?

Thx

**Comment by MishkaRogachev** [comment]
Hi. Yes, old jagcs version supports multi vehicle control, but displays indicators and controls ony for one vehicle at time. You can switch between vehicles in combo. But on the map you can see all the vehicles and missions in system. Newer version (i will release it soon) will include special mode, where you can control several vehicles at time.
