### ISSUE TITLE
Can't build on Linux Ubuntu

### ISSUE THREAD

**Issue by Duds** [MishkaRogachev/JAGCS#33]
Hi Mishka, I'm new to Linux but slowly getting up to speed. I tried following the instructions and got the following error.
`CMake Error at CMakeLists.txt:47 (find_package):
  By not providing "FindQt5.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5" with any of
  the following names:

```
    Qt5Config.cmake
    qt5-config.cmake
Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR"
to a directory containing one of the above files.  If "Qt5" provides a
separate development package or SDK, be sure it has been installed.

-- Configuring incomplete, errors occurred!
See also "/home/dale/JAGCS/build/CMakeFiles/CMakeOutput.log".'
```

How do I set up QT5?

**Comment by MishkaRogachev** [comment]
Hi! JAGCS can be build only with Qt version > 5.9, so i recommend to install auxillary package in /opt form [Qt official site](https://www.qt.io/download-qt-installer). Since Ubuntu18.04 LTS release you can use system Qt, but you will need to install[dev packages](https://askubuntu.com/questions/508503/whats-the-development-package-for-qt5-in-14-04).

**Comment by charles200000** [comment]
hello, 
me too I have the same problem but I don't really understand what you mean by : " i recommend to install the auxiliary package in /opt form Qt official site."

can you just explain a bit more please ? :)

**Comment by charles200000** [comment]
So I have finally fixed the issue, you need to add those three lines into the CMakeLists : 

set(Qt5Core_DIR "/opt/Qt5/5.9.1/gcc_64/lib/cmake/Qt5Core")
set(Qt5_DIR "/opt/Qt5/5.9.1/gcc_64/lib/cmake/Qt5")
set(QT_QMAKE_EXECUTABLE "/opt/Qt5/5.9.1/gcc_64/bin/qmake")


this is to change the Qt5 library directory... If you have other questions just ask I may can help you out

**Comment by MishkaRogachev** [comment]
18.04 ships with Qt 5.9.5 by default. I will do minor release in a few days including build instructions and binaries for ubuntu

**Comment by MishkaRogachev** [comment]
https://github.com/MishkaRogachev/JAGCS/wiki/Building-on-Linux
