### ISSUE TITLE
How to compile with MapBox GL?

### ISSUE THREAD

**Issue by shujaatak** [MishkaRogachev/JAGCS#35]
Just tried JAGCS (Just Awesome GCS) & It is impressive! 🥇 
By the way, How can I compile it with MapBox GL? Can you please mention the steps required to smoothly compile JAGCS with MapBox GL please?

Edit: I am using Windows 10, Qt5.10.1/Qt5.11

**Comment by MishkaRogachev** [comment]
Hello, thank you! 
You can compile it with MapBox GL using the cmake option:
`cmake .. -DWITH_MAPBOXGL=ON`
By the way, i'm working on [wiki](https://github.com/MishkaRogachev/JAGCS/wiki) right now

**Comment by shujaatak** [comment]
Oh is it that simple?
I have got to learn reading cmake project files :)
