### ISSUE TITLE
Unexpected waypoint drag and release response

### ISSUE THREAD

**Issue by shujaatak** [MishkaRogachev/JAGCS#36]
I accidentally dragged a waypoint and released in one of the top and left panels and in response the waypoint disappeared with lat lon equal to 0.
I think the waypoint shouldn't be moved at all when such scenario occur.
![issue](https://user-images.githubusercontent.com/14161646/42139513-b6389cdc-7da8-11e8-8042-e22091f9a95a.png)
![issue_](https://user-images.githubusercontent.com/14161646/42139516-ba089e98-7da8-11e8-825d-8a40235348a4.PNG)

**Comment by MishkaRogachev** [comment]
Now the map will pan if you try to set point outside borders.
