### ISSUE TITLE
visual studio 2015 qt5.9.2

### ISSUE THREAD

**Issue by OmarHamdoun** [MishkaRogachev/JAGCS#40]
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2131	expression did not evaluate to a constant	jagcs	D:\JAGCS\sources\communication\communicators\mavlink\mode_helpers\px4_mode_helper.cpp	50

**Comment by MishkaRogachev** [comment]
It seem to be a visual studio bug, 2015 does not have full support of the C++11 standart. May be this update will help: https://blogs.msdn.microsoft.com/vcblog/2015/12/02/constexpr-in-vs2015-update-1/
