### ISSUE TITLE
UDP links overlapping

### ISSUE THREAD

**Issue by nnhw** [MishkaRogachev/JAGCS#50]
I connected JAGCS usin UDP link to device on different PC in my sub network, port 14550. Then, I launched APM sitl, obviously on 14550 too, but on localhost. Data gets overlapped

**Comment by nnhw** [comment]
maybe, i could be SITL problems

**Comment by MishkaRogachev** [comment]
If you have several data sources sending on one port, you will get all the data on in one link. But if data separated by MAVLink packets, it does not make a problem. You shoul only have different MAVLink identificators of data sources
