### ISSUE TITLE
Text in Russian

### ISSUE THREAD

**Issue by nnhw** [MishkaRogachev/JAGCS#56]
Even when I choose English translation, there are map and time/date strings in Russian

![image](https://user-images.githubusercontent.com/37814163/46540358-c0947c00-c8c1-11e8-8b53-063f48a3aa44.png)

**Comment by MishkaRogachev** [comment]
Map tiles providers use local language. For time/date JAGCS use system locale, in next version (Fleet) i will add application's locale preferences
