### ISSUE TITLE
Sorting method

### ISSUE THREAD

**Issue by nnhw** [MishkaRogachev/JAGCS#69]
Right now, JAGCS sorts lists like this:

- 1
- 10
- 11
- 2
- 3
- 4
- 5
- 6
- 7

or 

- 1
- 2
- 253
- 254
- 255
- 3
- 4

Its more convenient to have natural ascending order

**Comment by nnhw** [comment]
In addition, it would be useful to have different sorting methods - distance, altitude, speed, etc. In descending and ascending order.

**Comment by MishkaRogachev** [comment]
Ready!
